# Generated by Django 3.2.8 on 2021-10-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oracle_id', models.UUIDField()),
                ('arena_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('layout', models.TextField(max_length=20)),
                ('mana_cost', models.CharField(blank=True, max_length=200, null=True)),
                ('type_line', models.CharField(blank=True, max_length=200, null=True)),
                ('set', models.CharField(max_length=200)),
                ('collector_number', models.CharField(max_length=200)),
                ('set_name', models.CharField(max_length=200)),
                ('oracle_text', models.TextField(blank=True, max_length=200, null=True)),
                ('image_url_small', models.TextField(blank=True, max_length=200, null=True)),
                ('image_url_normal', models.TextField(blank=True, max_length=200, null=True)),
                ('image_url_art_crop', models.TextField(blank=True, max_length=200, null=True)),
                ('alt_image_url_small', models.TextField(blank=True, max_length=200, null=True)),
                ('alt_image_url_normal', models.TextField(blank=True, max_length=200, null=True)),
                ('alt_image_url_art_crop', models.TextField(blank=True, max_length=200, null=True)),
                ('legalities', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
