# Generated by Django 3.2.8 on 2021-10-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardhandler', '0002_alter_card_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='rarity',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
