# Generated by Django 3.2.8 on 2021-10-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badhistoricdecks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='format',
            field=models.CharField(choices=[('HIS', 'Historic'), ('STD', 'Standard')], max_length=40),
        ),
    ]
